-- =============================================================================
-- gold/kitchen_efficiency.sql
-- Dynamic Table: Real-time kitchen efficiency score (refreshes every 5 min)
-- =============================================================================

-- External volume for Iceberg integration
CREATE EXTERNAL VOLUME IF NOT EXISTS restaurant_data_volume
  STORAGE_LOCATIONS = (
    (
      NAME                    = 'primary'
      STORAGE_PROVIDER        = 'S3'
      STORAGE_BASE_URL        = 's3://restaurant-iceberg-prod/'
      STORAGE_AWS_ROLE_ARN    = 'arn:aws:iam::123456789012:role/snowflake-restaurant-role'
    )
  );

-- Iceberg table: orders from all locations via external Iceberg catalog
CREATE OR REPLACE ICEBERG TABLE ops.orders_realtime
  EXTERNAL_VOLUME = 'restaurant_data_volume'
  CATALOG         = 'SNOWFLAKE'
  BASE_LOCATION   = 'gold/orders/'
  CLUSTER BY (location_id, DATE(order_time));

-- Dynamic Table: kitchen efficiency KPIs (5-minute lag)
CREATE OR REPLACE DYNAMIC TABLE gold.kitchen_efficiency
  TARGET_LAG = '5 minutes'
  WAREHOUSE  = 'KITCHEN_ANALYTICS_WH'
  CLUSTER BY (location_id)
AS
SELECT
    o.location_id,
    DATE_TRUNC('hour', o.order_time)                                          AS hour,
    COUNT(*)                                                                   AS total_orders,
    ROUND(AVG(DATEDIFF('second', o.order_time, o.ready_time)), 1)             AS avg_prep_secs,
    ROUND(
      COUNT_IF(DATEDIFF('second', o.order_time, o.ready_time) > 600) / COUNT(*) * 100, 2
    )                                                                          AS pct_slow_orders,
    ROUND(AVG(k.temperature_f), 1)                                            AS avg_grill_temp_f,
    COUNT(DISTINCT k.station_id)                                               AS active_stations,
    MAX(DATEDIFF('second', o.order_time, o.ready_time))                       AS max_prep_secs
FROM ops.orders_realtime          o
LEFT JOIN ops.kitchen_telemetry   k
  ON  o.location_id              = k.location_id
  AND DATE_TRUNC('minute', o.order_time) = DATE_TRUNC('minute', k.timestamp)
  AND k.equipment_type           = 'grill'
GROUP BY
    o.location_id,
    DATE_TRUNC('hour', o.order_time);


-- =============================================================================
-- gold/dynamic_pricing.sql
-- =============================================================================

CREATE OR REPLACE TABLE gold.dynamic_pricing (
    location_id        VARCHAR(64)    NOT NULL,
    date               DATE           NOT NULL,
    demand_multiplier  NUMBER(5, 4)   NOT NULL DEFAULT 1.0000,
    created_at         TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    created_by         VARCHAR(128)   NOT NULL DEFAULT CURRENT_USER(),
    CONSTRAINT pk_dynamic_pricing PRIMARY KEY (location_id, date)
)
CLUSTER BY (location_id, date)
COMMENT = 'ML-generated demand multipliers pushed to delivery platforms every 15 min';


-- =============================================================================
-- gold/prep_lists.sql (generated by Airflow daily)
-- =============================================================================

CREATE OR REPLACE TABLE gold.prep_lists (
    location_id        VARCHAR(64)    NOT NULL,
    menu_item_id       VARCHAR(64)    NOT NULL,
    menu_item_name     VARCHAR(256),
    prep_quantity      NUMBER(10, 2)  NOT NULL,
    prep_time_minutes  INTEGER,
    priority           VARCHAR(16)    NOT NULL,   -- URGENT | STANDARD | MINIMAL
    generated_at       TIMESTAMP_NTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (location_id, priority)
COMMENT = 'Daily kitchen prep lists generated each morning before service';
